"""Replace is_deleted with deleted_at in Note model

Revision ID: 92f89d01467e
Revises: dd44d76a3142
Create Date: 2024-12-11 01:02:47.833737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92f89d01467e'
down_revision = 'dd44d76a3142'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###
